### PR TITLE
Feature/#24 store to buy items

### LINKED ISSUE #24: Shop
**Description:**
The player will be able to visit the shop to buy and preview items

**Given:** Player in main menu

**When:** Player presses the "Shop" button.

**Then:** Open  shop.

**Parent:**

**Child:**

**Area:**
Business

### PR DESCRIPTION
**Pull request by Vitalii4D5458**
Added store template

### CODE REVIEW

**Comment by Ostappp** [comment]
image

As I understood, the previous version of Text Mesh Pro has been used. Since I had to run with a problem during the building project, I have changed the version from TMP 3.0.2 to 3.2.0-pre.6. So, I think it would be better to check this to avoid conflicts in the future.

**Comment by Ostappp** [comment]
About my previous comment, I recommend having a conversation tomorrow.

**Review by Ostappp — DISMISSED** [review]

**Review by Evhenn — DISMISSED** [review]
Everything seems to be good

**Comment by Ostappp** [comment]
> Все ніби добре

Needed to fix level 1, curently in progress

**Comment by Ostappp** [comment]
Now lvl1 is fixed, so you may approve and complete the pull request

**Review by Evhenn — APPROVED** [review]
Everything seems to be alright

**Pull request merged**
